server:
  port: 8003

spring:
  application:
    name: oauth2-login
  security:
    oauth2:
      client:
        registration:
          messaging-client:
            provider: spring
            client-id: messaging-client
            client-secret: secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8003/login/oauth2/code/messaging-client
            scope: openid,profile,message.read,message.write
            client-name: Spring
        provider:
          spring:
            authorization-uri: http://localhost:8001/oauth2/authorize
            token-uri: http://localhost:8001/oauth2/token
            jwk-set-uri: http://localhost:8001/oauth2/jwks

logging:
  level:
    root: debug
    org.springframework.web: debug
    org.springframework.security: debug
    org.springframework.security.oauth2: debug
