server:
  port: 8001

spring:
  application:
    name: oauth2-auth
debug: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
