server:
  port: 8002

spring:
  application:
    name: oauth2-order

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8001/oauth2/jwks
#          issuer-uri: http://localhost:8001
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
